### ISSUE TITLE
playdarctl unexpected behaviour

### ISSUE THREAD

**Issue by jphastings** [RJ/playdar-core#13]
```
./playdarctl help
```

won't run without having playdar already started

**Comment by mxcl** [comment]
Difficult to fix seeing as the help comes from the erlang process. However maybe that can be moved into playdarctl.

**Comment by RJ** [comment]
the main issue is that the ctl commands are registered at runtime by whichever modules get loaded, so the playdarctl script can't know unless it asks a running instance.

**Comment by jphastings** [comment]
Could you hardcode a very brief start/stop help & usage description if there is no playdar instance found? or at least something saying 'playdar isn't running, try playdarctrl start & try again'?

**Comment by RJ** [comment]
This is what it says at the mo:

<pre>
$ ./playdarctl 
Failed to communicate with playdar@localhost: nodedown
Usage: playdarctl &lt;start|start-debug|stop|help&gt;
       (additional commands available once playdar is running)
</pre>

What would you recommend?

**Comment by jphastings** [comment]
The message it gives now is a lot more informative than I remember! (I think I was using the C client at the time? _Hangs head in shame for not posting version information_) This covers everything you'd need to know!
