### ISSUE TITLE
$@

### ISSUE THREAD

**Issue by lucasgonze** [RJ/playdar-core#5]
The issue:
lucas-gonzes-macbook-5:playdar-core lgonze$ ./playdarctl scan ~/Music/iTunes/iTunes\ Library
{"init terminating in do_boot",{undef,[{playdar_ctl,start,[]},{init,start_it,1},{init,start_em,1}]}}
Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
./playdarctl: line 48: [: too many arguments

The error at line 48 in playdarctl is that $@ is sometimes multiple strings, so the if statement is evaluating as 
if [ ! "string 1" "string 2" = "stop" ]
which of course doesn't work.

Just use $1 instead of $@ and it should still work, given that "stop" never takes arguments.

**Comment by RJ** [comment]
fixed, thanks!
