### ISSUE TITLE
Restrict mimetypes per query

### ISSUE THREAD

**Issue by RJ** [RJ/playdar-core#9]
eg, dispatch a query but only want mp3/aac results, because i'm using flash.

add to the qry:

"mimetypes" : [ "audio/mpeg", "audio/aac" ],

**Comment by RJ** [comment]
support mimetype filtering per query. closed by a12bac437f3e9c7f0576536c46e2f0f2d10002e9
/api/?method=resolve&mimetypes=audio/mpeg,audio/flac&artist=...
the query object becomes:
{
    artist: "foo"
    mimetypes: [ "audio/mpeg", "audio/flac" ],
    ...
}

**Comment by jwheare** [comment]
Now implemented in playdar.js

http://github.com/jwheare/playdar.js/commit/2660c3bf3d8c93ea6148a42e893724cee45296d8
